/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import apitest.Bing;
import apitest.Google;
import apitest.Result;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import metamotor.Operaciones;
import metamotor.Stemmer;
import persistencia.Query;
import persistencia.Query2;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import persistencia.Documento;
import persistencia.Yahoo;

/**
 *
 * @author EOMS
 */
public class Inter extends javax.swing.JFrame {

    Operaciones op;
    Stemmer stemmer;
    ArrayList<String> stemsArray = null;
    Query2 queryArray[];
    ArrayList<Query2> queryList;
    Documento documento;
    Yahoo yahooResult;

    public Inter() {
        op = new Operaciones();
        stemmer = new Stemmer();
        documento = new Documento();
        yahooResult = new Yahoo();
        op.setK(10);
        initComponents();
    }
    
    public void Reduce(){
        while((op.google+op.yahoo+op.bing+op.motor) > op.k){
            op.google--;
            op.yahoo--;
            op.motor--;
            op.bing--;
        }
        
        while((op.google+op.yahoo+op.bing+op.motor) < op.k){
            op.google++;
            op.yahoo++;
            op.motor++;
            op.bing++;
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Consulta");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Número de resultados");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("META-MOTOR DE BÚSQUEDA");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String consulta = (String) jTextField1.getText();
        String[] consultaArray = consulta.split(" ");
        jTextArea1.setText("");
        ArrayList<Result> googleResults = null;
        ArrayList<Result> bingResults = null;

        try {
            stemsArray = stemmer.Stem(consulta);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }


        op.createQuery0();
        op.createQuery1(stemsArray);
        if (jTextField2.getText() != null) {
            op.k = Integer.parseInt(jTextField2.getText());
        }
        op.getConsultasElegidas();
        op.getConsultasDePrueba();
        op.getRepresentativos();
        op.distEucl();
        op.getDocsPorQuery();
        op.getTotalDocs();

        /*Busca en el recuperador de documentos*/
        //Inserta la consulta a la tabla consulta
        op.GenericStoredProc("", "", "consulta");
        op.createQuery(stemsArray);
        queryArray = op.SimDocCons2("cosenoPT", "consulta");
        queryList = new ArrayList<Query2>(Arrays.asList(queryArray));
        Collections.sort(queryList);

        Reduce();
        try {
            //Google
            Google google = new Google();
            google.search(consulta, op.google);
            googleResults = google.getResults();
            System.out.println(op.google);
            //Bing
            Bing bing = new Bing();
            bing.search(consulta, op.bing);
            bingResults = bing.getResults();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        if (googleResults.size() > 0) {
            jTextArea1.append("Google\n\n");
            for (int i = 0; i < googleResults.size(); i++) {
                jTextArea1.append(googleResults.get(i) + "\n");
                jTextArea1.append("\n");
            }
        }

        if (bingResults.size() > 0) {
            jTextArea1.append("\nBing\n\n");
            for (int i = 0; i < bingResults.size(); i++) {
                jTextArea1.append(bingResults.get(i) + "\n");
                jTextArea1.append("\n");
            }
        }
        
        if (op.yahoo > 0) {
            jTextArea1.append("\nYahoo!\n\n");
            for (int i = 0; i < op.yahoo; i++) {
                jTextArea1.append(yahooResult.resultados[i] + "\n");
                jTextArea1.append("\n");
            }
        }
        
        

        if (op.motor > 0) {
            jTextArea1.append("\nRecuperador de documentos\n\n");
            for (int i = 0; i < op.motor; i++) {
                jTextArea1.append("Documento " + queryList.get(i).getUri() + "\n"
                        + documento.baseDeDocs.get(new Integer(queryList.get(i).getUri())) + "\n");
                jTextArea1.append("\n");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inter.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inter.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inter.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inter.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
